[2024-05-15T21:56:30.673+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: upload_csv_to_gcs_bucket.upload_task_1 scheduled__2022-08-13T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
