[2024-05-15T20:20:47.905+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 manual__2024-05-15T14:21:46.627429+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-05-15T22:23:24.613+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 manual__2024-05-15T14:21:46.627429+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
