[2024-05-15T14:40:20.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T14:40:20.669+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-15T00:00:00+00:00 [queued]>
[2024-05-15T14:40:20.685+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-15T00:00:00+00:00 [queued]>
[2024-05-15T14:40:20.687+0000] {taskinstance.py:2303} INFO - Starting attempt 11 of 12
[2024-05-15T14:40:20.716+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_task_0> on 2022-08-15 00:00:00+00:00
[2024-05-15T14:40:20.727+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=827) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-15T14:40:20.730+0000] {standard_task_runner.py:63} INFO - Started process 853 to run task
[2024-05-15T14:40:20.735+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_csv_to_gcs_bucket', 'upload_task_0', 'scheduled__2022-08-15T00:00:00+00:00', '--job-id', '720', '--raw', '--subdir', 'DAGS_FOLDER/gcp_csv_upload.py', '--cfg-path', '/tmp/tmpnwiaur4l']
[2024-05-15T14:40:20.741+0000] {standard_task_runner.py:91} INFO - Job 720: Subtask upload_task_0
[2024-05-15T14:40:20.777+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-15T14:40:20.859+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-15T00:00:00+00:00 [running]> on host e9b4a57d7285
[2024-05-15T14:40:21.090+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_csv_to_gcs_bucket' AIRFLOW_CTX_TASK_ID='upload_task_0' AIRFLOW_CTX_EXECUTION_DATE='2022-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-15T00:00:00+00:00'
[2024-05-15T14:40:21.101+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T14:40:21.180+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-15T14:40:21.188+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-15T14:40:21.190+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T14:40:21.192+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /data/sales_2022-08-15.csv
[2024-05-15T14:40:21.224+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_csv_to_gcs_bucket, task_id=upload_task_0, execution_date=20220815T000000, start_date=20240515T144020, end_date=20240515T144021
[2024-05-15T14:40:21.262+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 720 for task upload_task_0 (/data/sales_2022-08-15.csv; 853)
[2024-05-15T14:40:21.321+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T14:40:21.358+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T14:40:21.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
