[2024-05-13T21:31:43.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T21:31:43.467+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T21:22:15.823713+00:00 [queued]>
[2024-05-13T21:31:43.491+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T21:22:15.823713+00:00 [queued]>
[2024-05-13T21:31:43.492+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-05-13T21:31:43.549+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_to_gcs> on 2024-05-13 21:22:15.823713+00:00
[2024-05-13T21:31:43.566+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=135) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T21:31:43.571+0000] {standard_task_runner.py:63} INFO - Started process 146 to run task
[2024-05-13T21:31:43.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_upload_example', 'upload_file_to_gcs', 'manual__2024-05-13T21:22:15.823713+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/gcp_example.py', '--cfg-path', '/tmp/tmpoy8d1s94']
[2024-05-13T21:31:43.577+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask upload_file_to_gcs
[2024-05-13T21:31:43.612+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-13T21:31:43.694+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T21:22:15.823713+00:00 [running]> on host 9df925c47a8b
[2024-05-13T21:31:43.926+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_upload_example' AIRFLOW_CTX_TASK_ID='upload_file_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T21:22:15.823713+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T21:22:15.823713+00:00'
[2024-05-13T21:31:43.930+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T21:31:44.034+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-13T21:31:44.037+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-13T21:31:44.038+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T21:31:44.040+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /lesson_10/data/sales_clean.csv
[2024-05-13T21:31:44.064+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_upload_example, task_id=upload_file_to_gcs, execution_date=20240513T212215, start_date=20240513T213143, end_date=20240513T213144
[2024-05-13T21:31:44.085+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task upload_file_to_gcs (/lesson_10/data/sales_clean.csv; 146)
[2024-05-13T21:31:44.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T21:31:44.157+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T21:31:44.171+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
