[2024-05-15T14:39:30.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T14:39:31.027+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_csv_to_gcs_bucket.upload_task_1 manual__2024-05-15T14:16:38.900056+00:00 [queued]>
[2024-05-15T14:39:31.045+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_csv_to_gcs_bucket.upload_task_1 manual__2024-05-15T14:16:38.900056+00:00 [queued]>
[2024-05-15T14:39:31.048+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 6
[2024-05-15T14:39:31.122+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_task_1> on 2024-05-15 14:16:38.900056+00:00
[2024-05-15T14:39:31.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_csv_to_gcs_bucket', 'upload_task_1', 'manual__2024-05-15T14:16:38.900056+00:00', '--job-id', '707', '--raw', '--subdir', 'DAGS_FOLDER/gcp_csv_upload.py', '--cfg-path', '/tmp/tmpxtir_zjk']
[2024-05-15T14:39:31.165+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=805) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-15T14:39:31.167+0000] {standard_task_runner.py:91} INFO - Job 707: Subtask upload_task_1
[2024-05-15T14:39:31.168+0000] {standard_task_runner.py:63} INFO - Started process 820 to run task
[2024-05-15T14:39:31.205+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-15T14:39:31.296+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_csv_to_gcs_bucket.upload_task_1 manual__2024-05-15T14:16:38.900056+00:00 [running]> on host e9b4a57d7285
[2024-05-15T14:39:31.616+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_csv_to_gcs_bucket' AIRFLOW_CTX_TASK_ID='upload_task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T14:16:38.900056+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-15T14:16:38.900056+00:00'
[2024-05-15T14:39:31.645+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T14:39:31.804+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-15T14:39:31.810+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-15T14:39:31.818+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T14:39:31.823+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /data/2024-05-15.csv
[2024-05-15T14:39:31.845+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_csv_to_gcs_bucket, task_id=upload_task_1, execution_date=20240515T141638, start_date=20240515T143931, end_date=20240515T143931
[2024-05-15T14:39:31.868+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 707 for task upload_task_1 (/data/2024-05-15.csv; 820)
[2024-05-15T14:39:31.901+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T14:39:31.932+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T14:39:31.937+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
