[2024-05-15T14:39:27.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T14:39:27.828+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2024-05-15T14:39:27.847+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2024-05-15T14:39:27.849+0000] {taskinstance.py:2303} INFO - Starting attempt 10 of 11
[2024-05-15T14:39:27.891+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_task_0> on 2022-08-14 00:00:00+00:00
[2024-05-15T14:39:27.903+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=765) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-15T14:39:27.907+0000] {standard_task_runner.py:63} INFO - Started process 790 to run task
[2024-05-15T14:39:27.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_csv_to_gcs_bucket', 'upload_task_0', 'scheduled__2022-08-14T00:00:00+00:00', '--job-id', '693', '--raw', '--subdir', 'DAGS_FOLDER/gcp_csv_upload.py', '--cfg-path', '/tmp/tmp8327gc93']
[2024-05-15T14:39:27.918+0000] {standard_task_runner.py:91} INFO - Job 693: Subtask upload_task_0
[2024-05-15T14:39:27.958+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-15T14:39:28.041+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-14T00:00:00+00:00 [running]> on host e9b4a57d7285
[2024-05-15T14:39:28.218+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_csv_to_gcs_bucket' AIRFLOW_CTX_TASK_ID='upload_task_0' AIRFLOW_CTX_EXECUTION_DATE='2022-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-14T00:00:00+00:00'
[2024-05-15T14:39:28.220+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T14:39:28.272+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-15T14:39:28.277+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-15T14:39:28.279+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T14:39:28.281+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /data/2022-08-14.csv
[2024-05-15T14:39:28.299+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_csv_to_gcs_bucket, task_id=upload_task_0, execution_date=20220814T000000, start_date=20240515T143927, end_date=20240515T143928
[2024-05-15T14:39:28.328+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 693 for task upload_task_0 (/data/2022-08-14.csv; 790)
[2024-05-15T14:39:28.380+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T14:39:28.421+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T14:39:28.427+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
