[2024-05-14T10:57:47.059+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T10:57:47.133+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:13:46.263335+00:00 [queued]>
[2024-05-14T10:57:47.174+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:13:46.263335+00:00 [queued]>
[2024-05-14T10:57:47.177+0000] {taskinstance.py:2303} INFO - Starting attempt 21 of 22
[2024-05-14T10:57:47.226+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_to_gcs> on 2024-05-13 20:13:46.263335+00:00
[2024-05-14T10:57:47.248+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_upload_example', 'upload_file_to_gcs', 'manual__2024-05-13T20:13:46.263335+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/gcp_cloud_sales.py', '--cfg-path', '/tmp/tmpoz574fum']
[2024-05-14T10:57:47.254+0000] {standard_task_runner.py:91} INFO - Job 257: Subtask upload_file_to_gcs
[2024-05-14T10:57:47.251+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=359) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T10:57:47.256+0000] {standard_task_runner.py:63} INFO - Started process 365 to run task
[2024-05-14T10:57:47.289+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-14T10:57:47.383+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:13:46.263335+00:00 [running]> on host e9b4a57d7285
[2024-05-14T10:57:47.625+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_upload_example' AIRFLOW_CTX_TASK_ID='upload_file_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T20:13:46.263335+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T20:13:46.263335+00:00'
[2024-05-14T10:57:47.630+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T10:57:47.702+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-14T10:57:47.711+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-14T10:57:47.716+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T10:57:47.760+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 110, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 525, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 168, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 307, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 284, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 213, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-05-14T10:57:47.769+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_upload_example, task_id=upload_file_to_gcs, execution_date=20240513T201346, start_date=20240514T105747, end_date=20240514T105747
[2024-05-14T10:57:47.803+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 257 for task upload_file_to_gcs (The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 365)
[2024-05-14T10:57:47.862+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-14T10:57:47.925+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T10:57:47.929+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
