[2024-05-13T21:32:17.884+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T21:32:17.924+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:13:46.263335+00:00 [queued]>
[2024-05-13T21:32:17.947+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:13:46.263335+00:00 [queued]>
[2024-05-13T21:32:17.948+0000] {taskinstance.py:2303} INFO - Starting attempt 11 of 12
[2024-05-13T21:32:17.984+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_to_gcs> on 2024-05-13 20:13:46.263335+00:00
[2024-05-13T21:32:18.004+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T21:32:18.013+0000] {standard_task_runner.py:63} INFO - Started process 173 to run task
[2024-05-13T21:32:18.014+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_upload_example', 'upload_file_to_gcs', 'manual__2024-05-13T20:13:46.263335+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/gcp_example.py', '--cfg-path', '/tmp/tmpa8o_85za']
[2024-05-13T21:32:18.018+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask upload_file_to_gcs
[2024-05-13T21:32:18.062+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-13T21:32:18.154+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:13:46.263335+00:00 [running]> on host 9df925c47a8b
[2024-05-13T21:32:18.514+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_upload_example' AIRFLOW_CTX_TASK_ID='upload_file_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T20:13:46.263335+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T20:13:46.263335+00:00'
[2024-05-13T21:32:18.528+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T21:32:18.600+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-13T21:32:18.604+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-13T21:32:18.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T21:32:18.606+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: ./lesson_10/data/sales_clean.csv
[2024-05-13T21:32:18.628+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_upload_example, task_id=upload_file_to_gcs, execution_date=20240513T201346, start_date=20240513T213217, end_date=20240513T213218
[2024-05-13T21:32:18.652+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 103 for task upload_file_to_gcs (./lesson_10/data/sales_clean.csv; 173)
[2024-05-13T21:32:18.692+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T21:32:18.877+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T21:32:18.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
